### ISSUE TITLE
I cannot for the life of me include this inside my Podfile with Cocoapods 0.36.0.rc.1

### ISSUE THREAD

**Issue by gotnull** [Yalantis/Persei#1]
I add the following to my Podfile:
# required by Cocoapods 0.36.0.rc.1 for Swift Pods

use_frameworks! 

pod 'Persei', '~> 1.0'

Run "pod install" via the commandline.

It installs it successfully, but then I go ahead and compile my project and I get all sorts of errors where it can't find existing Pod frameworks that used to compile successfully.

E.g.:

ld: warning: directory not found for option '-L/Users/scott/Desktop/MyApp/Pods/build/Debug-iphoneos'
ld: framework not found FCVerticalMenu
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by dimazen** [comment]
@gotnull 
Hm, what it you're removing 
`use_frameworks! pod 'Persei', '~> 1.0'`
and re-run install? Is it fixed? 

It appears that FCVerticalMenu can't be build as a framework (assumed), probably it can't be build as a framework. What is the deployment iOS version of your app?

**Comment by dimazen** [comment]
@gotnull 
Probably, you're building for iOS 7, and it doesn't support dynamic frameworks.
