### ISSUE TITLE
Swift 2.0

### ISSUE THREAD

**Issue by TayfunAslan** [Yalantis/Persei#10]
Hello,

I'm using Xcode 7.0 Beta 2, your library and triggers many errors.
You're currently creating a branch to solve this problem?

Thanks.

**Comment by dimazen** [comment]
Hello, @TayfunAslan 
Currently there are no plans to migrate on swift 2.0 
However I believe there are not a lot to fix there

**Comment by Art3mS1d** [comment]
Hello, @TayfunAslan 
We created branch to maintain Swift 2.0 
https://github.com/Yalantis/Persei/tree/swift_2.0

**Comment by TayfunAslan** [comment]
@artemSydorenko Ok, Thanks !
