### ISSUE TITLE
Turn bounces off without removing the menu.

### ISSUE THREAD

**Issue by ArthurU** [Yalantis/Persei#14]
I was wondering if there was a way to turn bounces off in the tableView without stopping the Persei menu from appearing?

**Comment by dimazen** [comment]
@ArthurU not sure I got your idea. Can you add some sort of image or some kind of a description?

**Comment by ArthurU** [comment]
<img width="369" alt="screen shot 2015-08-15 at 17 17 11" src="https://cloud.githubusercontent.com/assets/10178361/9289480/80bf32b0-4371-11e5-9758-93166674a2b8.png">

**Comment by ArthurU** [comment]
There we go, there is a lot of space at the top, and I was just wondering if there was a way to avoid that stretch.

**Comment by dimazen** [comment]
Oh, I got it. Let me make an update.

**Comment by dimazen** [comment]
Update to the (https://github.com/Yalantis/Persei/releases/tag/1.1) version with new `StickyHeaderView.contentViewGravity` variable. 

Usage:

```
let headerView = MenuView() 
headerView.contentViewGravity = .Top
```
