### ISSUE TITLE
Unfortunately not runnning on XCode7/Swift2

### ISSUE THREAD

**Issue by headkit** [Yalantis/Persei#18]
Any chnace for a fix for this nice little menu...?

**Comment by dimazen** [comment]
@headkit 
Thanks for usage! 
Please, check out version 2.0!

**Comment by headkit** [comment]
I would - but I get the error

Example-Bridging-Header.h:5:9: 'UIImage_Autoresize/UIImage+Autoresize.h' file not found

**Comment by dimazen** [comment]
@headkit Are you talking about Example app? 
What versions of Xcode and Cocoapods do you use?

**Comment by headkit** [comment]
XCode 7.0.1 without Cocoapods

**Comment by dimazen** [comment]
@headkit Hm, for some reason .xcworspace file wasn't added to the git. 
Please, run `pod install` in the root of the sample app like this:

```
cd Persei/Example
pod install
open Example.xcworkspace
```

**Comment by dimazen** [comment]
Seems to be related to the #16

**Comment by headkit** [comment]
Yes. :-) Would be awesome if itwould run without pod, too!

**Comment by dimazen** [comment]
@headkit I've removed cocoapods from the sample app in the [2.0.1](https://github.com/Yalantis/Persei/releases/tag/2.0.1)

**Comment by headkit** [comment]
hey, now it works - thanx!!
