### ISSUE TITLE
use Persei in objc project

### ISSUE THREAD

**Issue by NilStack** [Yalantis/Persei#2]
I want to use Persei in my objc project, but can't define MenuItem because it's Struct. So I simply changed MenuItem to class and subclass of NSObject. Maybe the requirement is a little weired and the solution has potential risk. What's your suggestion? @Yalantis Whatever, thanks for sharing Persei!

**Comment by dimazen** [comment]
Hello, @NilStack

**Comment by dimazen** [comment]
Hello, @NilStack 
`struct` is used to prevent unexpected changes of `MenuItem`
When we're declaring `MenuItem` as a class - user can change any of it's values with no restriction. 

Is there any way to rewrite your view controller on swift?

**Comment by NilStack** [comment]
Hi, @dimazen :
Thanks for your response and suggestion.
