### ISSUE TITLE
How to replace UIImage by UIView

### ISSUE THREAD

**Issue by Twelve57** [Yalantis/Persei#20]
Hi,
I've just git this project and I was wondering how do I change/replace the UIImage by something like an UIView ? 

I Hope you will answer me soon,
Regards.

**Comment by dimazen** [comment]
Hello, @Twelve57 
As far as I understood you're looking for a way to replace that UIImage icon with custom UIView, am I right? If so - no, you can not do this. However, I believe we can fix this easily by adding a `customView` property to the `MenuItem` and specific handling to the `MenuCell` just as `UIBarButtonItem` does :)

**Comment by dimazen** [comment]
Let me know exactly what you need, looks like it is a matter of 30 minutes.

**Comment by Twelve57** [comment]
Thanks for your answers.
I came up with another solution but what I wanted to do is like you said : use a customView in MenuView/MenuItem. The goal was to set up a container below the menu like an Android fragment.
