### ISSUE TITLE
not showing

### ISSUE THREAD

**Issue by codeSupreme** [Yalantis/Persei#21]
When my uicollectionview only has 1 item the menu does not show.  Is there a item count min?

**Comment by serejahh** [comment]
Hi @codeSupreme. Thanks for your interest to our component!
Have you already solved the problem? I've just tested with one item and it works properly:
![simulator screen shot 22 jul 2016 09 49 26](https://cloud.githubusercontent.com/assets/2575555/17048838/aaeb4f50-4ff1-11e6-965c-a588664f6aae.png)

**Comment by peterng014** [comment]
hi,
I have the same,
My collection view there are 4 items (2 cols, 2rows), it cannot scroll then the menu does not show.
Please verify it.
Thanks
