### ISSUE TITLE
Pull to refresh?

### ISSUE THREAD

**Issue by SebastianBO** [Yalantis/Persei#23]
Might not be the smartest UI wise, but is it possible to have a pull to refresh above here? Maybe i should try instead of asking...
Best Regards, great implementation! Super impressed by your work

**Comment by serejahh** [comment]
Hi @SebastianBO. Thanks for interest to our component! 
1. I'm afraid, it's not possible without changes in the component
2. You're completely right about UX — it wouldn't be obvious enough: you have to open the menu to refresh the data

Have a nice day 😉
