### ISSUE TITLE
setRevealed throwing as nil optional

### ISSUE THREAD

**Issue by MatrixSenpai** [Yalantis/Persei#24]
When I attempt to set the revealed state, the initialized MenuView returns as a nil optional.

My code

``` swift
// TableViewController properties
var picker: MenuView {
    let m = MenuView()
    // Init other options and add items
    return m
}
// -----------------------
override func viewWillAppear(animated: Bool) {
    picker.setRevealed(true, animated: true)
}
```

I have also tried setting m.revealed when initializing the property. I get the same error every time

Also good to note that this TVC is sometimes a child VC and sometimes not

**Comment by serejahh** [comment]
Hi @mathmatrix828. Thanks for interest to our component! 
Could you provide a test project?

**Comment by VidurMalik** [comment]
@serejahh @mathmatrix828  I was having the same issue on Swift 2.2.
Setting the `revealed` flag results in a nil optional being unwrapped in `viewDidLoad` and `viewWillAppear`.
It seems like the `superview` of the `StickyHeaderView` is nil, therefore, set the revealed flag in `viewWillAppear`. That is when the superview is set. This should solve it

**Comment by PravdaEvgen** [comment]
Fixed, check it out in new version
