### ISSUE TITLE
Sticky header View observer crash

### ISSUE THREAD

**Issue by siideffect** [Yalantis/Persei#25]
Hello, i am currently developing a project which uses this awesome library. Actually, i am developing with swift 3, using the xcode betas, and i was able to make it working without any trouble. My project is very close to be completed, but after i ve updated to xcode beta 6, ( and made some changes to library in order to make happy the compiler), my app is crashing every time i try to present the persei table. Through an exception breakpoint, the problem seems to be caused by 

```
public override func didMoveToSuperview() {
        super.didMoveToSuperview()

        if let view = superview as? UIScrollView {
//AddObserver makes the app crash
            view.addObserver(self, forKeyPath: "contentOffset", options: [.initial, .new], context: &ContentOffsetContext)
            view.panGestureRecognizer.addTarget(self, action: #selector(StickyHeaderView.handlePan(_:)))
            view.sendSubview(toBack: self)
        }
    }
```

Do you have any suggestion in order to make it work again as expected? The persei controller was totally integrated in my app, if i can t find a solution i will have to switch library for a new one and i wanna be sure it will be the last option. 
Thanks for your attention, hope all is gonna be solved

**Comment by serejahh** [comment]
Does it happen for Xcode 8 `release`? Can you reproduce the issue with the example app?

**Comment by siideffect** [comment]
Hello serejahh, i can t reply since i had to remove completely the persei library from my project due to this crash related to the observer. Thanks for reply, best regards!
