### ISSUE TITLE
Unable to update to 3.0 with cocoapods

### ISSUE THREAD

**Issue by mrigo** [Yalantis/Persei#27]
Hi!

I'm trying to update the Persei pod with cocoapods to use swift 3.0, in my Podfile I've added this line, like the readme file describes:

```
use_frameworks! 

pod 'Persei', '~> 3.0'
```

but I've this error

```
[!] Unable to satisfy the following requirements:

- `Persei (~> 3.0)` required by `Podfile`
- `Persei (~> 3.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Persei (~> 3.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

What can I do?

Thanks!
\m

**Comment by serejahh** [comment]
Hi @mrigo! Thanks for reporting the issue. We forgot to push a new podspec. Now everything should be ok. Please, check again

**Comment by mrigo** [comment]
Thanks @serejahh 
now it works like charms!

**Comment by serejahh** [comment]
Sounds great! 👍
