### ISSUE TITLE
No interaction on item click using iOS 7 iPhone 5 simulator

### ISSUE THREAD

**Issue by Aymenworks** [Yalantis/Persei#3]
Hello,

First of all, thanks you for this project.

I'm using Persei on my app and it works fine on iOS 8. However, the "didSelectRow" doesn't seems to work on iOS 7. It reveal normally the menu but there is no action when clicking on items.

Do you have an idea about this problem ?

Edited: The items thumbnails are also reduced.

**Comment by dimazen** [comment]
@Aymenworks I'll take a look on monday or tomorrow's evening

**Comment by dimazen** [comment]
@Aymenworks Hm, it appears, that embed collection view doesn't receive touches at all. 
Figuring out why.

**Comment by Aymenworks** [comment]
Hello @dimazen , did you find a way to resolve it ? 
I don't have the time this week but if you don't have time I'll check it maybe next week.

**Comment by dimazen** [comment]
hello, @Aymenworks 
It seems, that gesture recogniser of CollectionView prevented by someone else (tableview probably), but I haven't fixed it yet

**Comment by dimazen** [comment]
@Aymenworks 
During testing I've noticed several strange bugs due to some internal changes in UIScrollView. 
However, I'm busy on current project and have no time Persei iOS 7 in the closest few weeks :(

**Comment by serejahh** [comment]
Hi @dimazen
Could you describe all the bugs? I can fix it instead of you 😉
