### ISSUE TITLE
Menu Position error after upgrade to ios 11.0.3

### ISSUE THREAD

**Issue by Derek-X-Wang** [Yalantis/Persei#31]
Run the example project and this happens:

![img_2431](https://user-images.githubusercontent.com/6364170/31855472-be12dd9c-b660-11e7-8302-92e88a0a4dbd.PNG)

**Comment by Derek-X-Wang** [comment]
In ios11, apple changes the inset of uiscrollview to (0,0,0,0) instead of (64,0,49,0).

reset the inset manually will solve this problem
```
if #available(iOS 11.0, *) {
    collectionView?.contentInsetAdjustmentBehavior = .never
    collectionView?.contentInset = UIEdgeInsetsMake(64.0, 0, 49, 0)
}
```

anyone knows how to do this without hard code the inset?

**Comment by dimazen** [comment]
Hello, @Derek-X-Wang! We're planning to fix it tomorrow :)

**Comment by Derek-X-Wang** [comment]
Great! I'm looking forward to the new release!

**Comment by dimazen** [comment]
@Derek-X-Wang checkout release [3.1](https://github.com/Yalantis/Persei/releases/tag/3.1)! It fixes reported issue. 
Thanks for your support :)

**Comment by Derek-X-Wang** [comment]
The 3.1 doesn't compile in my app.
it says collectionlayout is inaccessible.
any idea?
![img_1957](https://user-images.githubusercontent.com/6364170/32046726-b32d1226-b9f8-11e7-825b-b8f0ec8b3268.JPG)

**Comment by dimazen** [comment]
@Derek-X-Wang I see. Looks like that you're using Swift 3. Am I right?

**Comment by dimazen** [comment]
@Derek-X-Wang I've rolled out [3.1.1](https://github.com/Yalantis/Persei/releases/tag/3.1.1) that allows you to use Persei under Swift 3.2. 
Ping me once your issue resolved. 

Thanks!

**Comment by Derek-X-Wang** [comment]
@dimazen You're right! I'm using Swift 3. v3.1.1 works like a charm! Amazing! Thanks for contributing such a great library!
