### ISSUE TITLE
Cannot import after cocopods install

### ISSUE THREAD

**Issue by cschelly** [Yalantis/Persei#34]
## Report a bug

This is in my Podfile 

pod ‘Persei’, ‘~> 3.1’

Running Swift 4 and Xcode 9 and whenever I try and import Persei I receive this error:

Cannot load underlying module for 'Persei'

![menutableviewcontroller swift 2017-12-24 16-36-21](https://user-images.githubusercontent.com/12465747/34329948-a41aa6dc-e8c8-11e7-8412-1c24581e9eab.png)

**Comment by srj0x0** [comment]
@cmsund Hi, thanks for your report! Try to remove import, build project and add it again.
