### ISSUE TITLE
contentsGravity in transformation only layer

### ISSUE THREAD

**Issue by 368433** [Yalantis/Persei#35]
# Report

> The more information you provide, the faster we can help you.

⚠️ Select what you want - **a feature request** or **report a bug**. Please remove the section you aren't interested in.

###  What did you do?

upon launching the application, the menu works well, but the console gives me the message:
"changing property contentsGravity in transform-only layer, will have no effect"
I have not changed contentsGravity. I have only implemented the menu in the most simple way as per instructions.

Again the application runs, the menu works, but I keep getting this message at

### What did you expect to happen?

Not get this message

### What happened instead?

Keep getting the message . Only upon launching the app it seems. When using in the simulator I do not get repeated messages

### Your Environment

- Version of the component: 3.0 latest as of writing
- Swift version: 4
- iOS version: 11
- Device: iphone 8 simulator
- Xcode version: 9.2
- If you use Cocoapods: _run `pod env | pbcopy` and insert here_ 
- If you use Carthage:
0.28.0

### Project that demonstrates the bug

> Please add a link to a project we can download that reproduces the bug.

**Comment by PravdaEvgen** [comment]
@368433 May be possible solution? https://stackoverflow.com/questions/33185720/changing-property-contentsgravity-in-transform-only-layer-will-have-no-effect
