### ISSUE TITLE
Menu disappears after triggering Control Center on iPhone X / Notifications on older iPhones.

### ISSUE THREAD

**Issue by miguelrc86** [Yalantis/Persei#36]
###  What did you do?

I accessed Control Center by swiping down from the top right corner.

**UPDATE:** It is also happening when triggering Notifications layer on older iPhones.

### What did you expect to happen?

When coming back from Control Center, the menu should still be functional.

### What happened instead?

The menu just disappeared, it didn't came back after scrolling or using the menu button of my implementation.

### Your Environment

- Version of the component: "Yalantis/Persei" "3.1.1"
- Swift version: 4.x
- iOS version: 11.4
- Device: iPhone X
- Xcode version: 9.4.1
- If you use Carthage: 0.30.1

![issueiphonex](https://user-images.githubusercontent.com/8277680/43040381-d757d61c-8d07-11e8-800a-eab4c950c212.gif)

**Comment by PravdaEvgen** [comment]
Hello, @miguelrc86, please check out the latest version of framework, I've checked your issue and couldn't reproduce it
