### ISSUE TITLE
ios 7 support

### ISSUE THREAD

**Issue by hpchemgio** [Yalantis/Persei#5]
Dear friend,

Thank you for your masterpiece of work. I've tried to use your nice library in my project which is support ios 7, but I got this error when updating pod:

[!] The platform of the target `TabDemo` (iOS 7.0) is not compatible with `Persei (1.0)` which has a minimum requirement of iOS 8.0.

Below is my podfile's content:

platform :ios, '7.0'

target 'TabDemo' do
use_frameworks!
pod 'Persei'
end

target 'TabDemoTests' do

end

Do your library still support ios 7?

Thank you so much

**Comment by dimazen** [comment]
Hello, @hpchemgio 
Since swift pods integrated by cocoa pods only as a dynamic frameworks - minimum iOS version is 8.0. 
However, you _can_ add it by a simple drag-and-drop. 
Please, note that this component was designed for iOS 8 and can have some issues on iOS 7 :(

**Comment by hpchemgio** [comment]
Dear @dimazen 

Thank you, I got it.

:)
