### ISSUE TITLE
Swift 1.2 Xcode 6.3 -Missing argument for parameter 'coder' in call

### ISSUE THREAD

**Issue by Rollersway** [Yalantis/Persei#7]
Persei-master/Example/Example/Controllers/ViewController.swift:23:28: Missing argument for parameter 'coder' in call

**Comment by Rollersway** [comment]
Solved just add: let menu:MenuView? = MenuView(frame: CGRect(x: 0, y: 0, width: 320, height: DefaultContentHeight))

**Comment by dimazen** [comment]
@Rollersway 
Thanks, I'll push an update tomorrow

**Comment by dimazen** [comment]
[1.0.1](https://github.com/Yalantis/Persei/releases/tag/1.0.1) pushed to the pod spec!
