### ISSUE TITLE
Keeping menu collectionview top to of tableview at all times

### ISSUE THREAD

**Issue by johnamcruz** [Yalantis/Persei#9]
I noticed that if you pull the collectionview down further it will move down. Is there a way to lock the menu collectionview so it stays on the top regardless?

**Comment by dimazen** [comment]
@johnamcruz I'm sure this feature can be added quite easily. 
Probably, I'll try to reuse UIView.contentMode in order to achieve different layout "gravity".

**Comment by dimazen** [comment]
@johnamcruz if you really need this feature urgent go to https://github.com/Yalantis/Persei/blob/master/Persei/Source/Core/StickyHeaderView.swift#L236

Roughly you need to replace this line by y: bounds.height - contentHeight

**Comment by dimazen** [comment]
@johnamcruz if this is still relevant check out version [1.1](https://github.com/Yalantis/Persei/releases/tag/1.1) with new `StickyHeaderView.contentViewGravity` variable. 

Usage:

```
let headerView = MenuView() 
headerView.contentViewGravity = .Top
```
